dump-restore-version: [[
  {
    version: source.latest,
    dump-data-as: copy,
    dump-format: plain,
    logical-database: null
  },
  {
    version: target.latest,
    dump-data-as: copy,
    dump-format: plain,
    logical-database: null
  }
],
[
  {
    version: source.latest,
    dump-data-as: copy,
    dump-format: custom,
    logical-database: master
  },
  {
    version: target.latest,
    dump-data-as: copy,
    dump-format: custom,
    logical-database: master
  }
],
[
  {
    version: source.latest,
    dump-data-as: inserts,
    dump-format: tar,
    logical-database: null
  },
  {
    version: target.latest,
    dump-data-as: inserts,
    dump-format: tar,
    logical-database: null
  }
],
[
  {
    version: source.latest,
    dump-data-as: inserts,
    dump-format: directory,
    logical-database: master
  },
  {
    version: target.latest,
    dump-data-as: inserts,
    dump-format: directory,
    logical-database: master
  }
],
[
  {
    version: source.latest,
    dump-data-as: copy,
    dump-format: plain,
    logical-database: database1
  },
  {
    version: target.latest,
    dump-data-as: copy,
    dump-format: plain,
    logical-database: database1
  }
]]
