dump-restore-version: [[
  {
    version: source.latest,
    dump-data-as: copy,
    dump-format: plain,
    database-level: false,
    type: full
  },
  {
    version: target.latest,
    dump-data-as: copy,
    dump-format: plain,
    database-level: false,
    type: full
  }
],
[
  {
    version: source.latest,
    dump-data-as: copy,
    dump-format: plain,
    database-level: false,
    type: schema-cum-data-only
  },
  {
    version: target.latest,
    dump-data-as: copy,
    dump-format: plain,
    database-level: false,
    type: schema-cum-data-only
  }
],
[
  {
    version: source.latest,
    dump-data-as: copy,
    dump-format: custom,
    database-level: true,
    type: full
  },
  {
    version: target.latest,
    dump-data-as: copy,
    dump-format: custom,
    database-level: true,
    type: full
  }
],
[
  {
    version: source.latest,
    dump-data-as: inserts,
    dump-format: tar,
    database-level: false,
    type: full
  },
  {
    version: target.latest,
    dump-data-as: inserts,
    dump-format: tar,
    database-level: false,
    type: full
  }
],
[
  {
    version: source.latest,
    dump-data-as: inserts,
    dump-format: custom,
    database-level: false,
    type: schema-cum-data-only
  },
  {
    version: target.latest,
    dump-data-as: inserts,
    dump-format: custom,
    database-level: false,
    type: schema-cum-data-only
  }
],
[
  {
    version: source.latest,
    dump-data-as: inserts,
    dump-format: directory,
    database-level: true,
    type: full
  },
  {
    version: target.latest,
    dump-data-as: inserts,
    dump-format: directory,
    database-level: true,
    type: full
  }
]]
