upgrade-version: [{
  upgrade-path: [
    {
      version: 13.6,
      upgrade-type: null
    },
    { 
      version: target.latest,
      upgrade-type: major
    }
  ]
},
{
  upgrade-path: [
    {
      version: 14.3,
      upgrade-type: null
    },
    { 
      version: target.latest,
      upgrade-type: minor 
    }
  ]
},
{
  upgrade-path: [
    {
      version: 14.5,
      upgrade-type: null
    },
    {
      version: target.latest,
      upgrade-type: minor
    }
  ]
},
{
  upgrade-path: [
    {
      version: '14.10',
      upgrade-type: null
    },
    {
      version: target.latest,
      upgrade-type: minor
    }
  ]
},
{
  upgrade-path: [
    {
      version: '14.11',
      upgrade-type: null
    },
    {
      version: target.latest,
      upgrade-type: minor
    }
  ]
},
{
  upgrade-path: [
    {
      version: '14.14',
      upgrade-type: null
    },
    {
      version: target.latest,
      upgrade-type: minor
    }
  ]
},
{
  upgrade-path: [
    {
      version: source.latest,
      upgrade-type: null
    },
    { 
      version: target.latest,
      upgrade-type: major
    }
  ]
},
{
  upgrade-path: [
    {
      version: 13.4,
      upgrade-type: null
    },
    { 
      version: 13.9,
      upgrade-type: minor 
    },
    { 
      version: target.latest,
      upgrade-type: major 
    }
  ]
},
{
  upgrade-path: [
    {
      version: 13.5,
      upgrade-type: null
    },
    { 
      version: 13.9,
      upgrade-type: minor 
    },
    { 
      version: target.latest,
      upgrade-type: major 
    }
  ]
},
{
  upgrade-path: [
    {
      version: 13.7,
      upgrade-type: null
    },
    { 
      version: target.latest,
      upgrade-type: major 
    }
  ]
},
{
  upgrade-path: [
    {
      version: 13.8,
      upgrade-type: null
    },
    { 
      version: target.latest,
      upgrade-type: major 
    }
  ]
},
{
  upgrade-path: [
    {
      version: 13.9,
      upgrade-type: null
    },
    { 
      version: target.latest,
      upgrade-type: major 
    }
  ]
},
{
  upgrade-path: [
    {
      version: 13.9,
      upgrade-type: null
    },
    { 
      version: target.latest,
      upgrade-type: major
    }
  ],
  babelfishpg_tsql_server_collation_name: chinese_prc_ci_as
},
{
  upgrade-path: [
    {
      version: 13.4,
      upgrade-type: null,
    },
    {
      version: 13.9,
      upgrade-type: minor,
    },
    { 
      version: target.latest,
      upgrade-type: major,
    }
  ],
  babelfishpg_tsql_server_collation_name: chinese_prc_ci_as
},
{
  upgrade-path: [
    {
      version: '14.10',
      upgrade-type: null,
    },
    { 
      version: target.latest,
      upgrade-type: minor,
    }
  ],
  babelfishpg_tsql_server_collation_name: chinese_prc_ci_as
},
{
  upgrade-path: [
    {
      version: '14.10',
      upgrade-type: null
    },
    { 
      version: target.latest,
      upgrade-type: minor
    }
  ],
  babelfishpg_tsql_server_collation_name: japanese_ci_as
}
]