upgrade-version: [[
  {
    version: 13.6,
    upgrade-type: null
  },
  { 
    version: 14.6,
    upgrade-type: major 
  },
  { 
    version: target.latest,
    upgrade-type: major 
  }
],
[
  {
    version: 13.9,
    upgrade-type: null
  },
  { 
    version: 14.6,
    upgrade-type: major 
  },
  { 
    version: target.latest,
    upgrade-type: major 
  }
],
[
  {
    version: 14.3,
    upgrade-type: null
  },
  {
    version: 14.6,
    upgrade-type: minor
  },
  { 
    version: target.latest,
    upgrade-type: major
  }
],
[
  {
    version: source.latest,
    upgrade-type: null
  },
  { 
    version: target.latest,
    upgrade-type: major
  }
],
[
  {
    version: 14.5,
    upgrade-type: null
  },
  { 
    version: 14.6,
    upgrade-type: minor 
  },
  { 
    version: target.latest,
    upgrade-type: major 
  }
]]
