name: JDBC Tests with Non Default Server Collation
on: [push, pull_request]

jobs:
  run-babelfish-jdbc-tests:
    env:
      INSTALL_DIR: psql
      SERVER_COLLATION_NAME: chinese_prc_ci_as

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        id: checkout

      - name: Install Dependencies
        id: install-dependencies
        if: always()
        uses: ./.github/composite-actions/install-dependencies

      - name: Build Modified Postgres
        id: build-modified-postgres
        if: always() && steps.install-dependencies.outcome == 'success'
        uses: ./.github/composite-actions/build-modified-postgres
      
      - name: Compile ANTLR
        id: compile-antlr
        if: always() && steps.build-modified-postgres.outcome == 'success'
        uses: ./.github/composite-actions/compile-antlr
      
      - name: Build Extensions
        id: build-extensions
        if: always() && steps.compile-antlr.outcome == 'success'
        uses: ./.github/composite-actions/build-extensions

      - name: Build tds_fdw Extension
        id: build-tds_fdw-extension
        if: always() && steps.build-extensions.outcome == 'success'
        uses: ./.github/composite-actions/build-tds_fdw-extension

      - name: Build vector Extension
        id: build-vector-extension
        if: always() &&  steps.build-tds_fdw-extension.outcome == 'success'
        uses: ./.github/composite-actions/build-vector-extension

      - name: Build PostGIS Extension
        id: build-postgis-extension
        if: always() &&  steps.build-vector-extension.outcome == 'success'
        uses: ./.github/composite-actions/build-postgis-extension

      - name: Install Extensions
        id: install-extensions
        if: always() && steps.build-postgis-extension.outcome == 'success'
        uses: ./.github/composite-actions/install-extensions
        with:
          server_collation_name: ${{ env.SERVER_COLLATION_NAME }}
          wal_level: logical

      - name: Run JDBC Tests
        id: jdbc
        if: always() && steps.install-extensions.outcome == 'success'
        timeout-minutes: 60
        run: |
          export PATH=~/${{env.INSTALL_DIR}}/bin:$PATH
          export PG_SRC=~/work/babelfish_extensions/postgresql_modified_for_babelfish
          cd test/JDBC/
          # set env variable serverCollationName to current server collation name
          export serverCollationName=${{ env.SERVER_COLLATION_NAME }}
          mvn test
          # reset env variable
          unset serverCollationName

      - name: Start secondary server
        id: start-secondary
        if: always() && steps.jdbc.outcome == 'success'
        uses: ./.github/composite-actions/install-extensions
        with:
          psql_port: 5433
          tsql_port: 8199
          wal_level: logical

      - name: Setup Publication and Subscription
        id: setup-pub-sub
        if: always() && steps.start-secondary.outcome == 'success'
        run: |
          ~/${{env.INSTALL_DIR}}/bin/psql -v ON_ERROR_STOP=1 -d jdbc_testdb -U runner -c "CREATE PUBLICATION my_pub;"
          ~/${{env.INSTALL_DIR}}/bin/psql -v ON_ERROR_STOP=1 -d jdbc_testdb -U runner -p 5433 -c "CREATE SUBSCRIPTION my_sub CONNECTION 'host=localhost port=5432 user=jdbc_user dbname=jdbc_testdb password=12345678' PUBLICATION my_pub;"

      - name: Run Replication Tests
        id: replication
        if: always() && steps.setup-pub-sub.outcome == 'success'
        timeout-minutes: 60
        uses: ./.github/composite-actions/run-jdbc-tests
        with:
          input_dir: 'replication'

      - name: Cleanup babelfish database
        id: cleanup
        if: always() && steps.replication.outcome == 'success'
        run: |
          sudo ~/psql/bin/psql -d postgres -U runner -v user="jdbc_user" -v db="jdbc_testdb" -f .github/scripts/cleanup_babelfish_database.sql

      - name: Upload Log
        if: always() && (steps.jdbc.outcome == 'failure' || steps.replication.outcome == 'failure')
        uses: actions/upload-artifact@v4
        with:
          name: postgres-log
          path: |
            ~/psql/data/logfile
            ~/psql/data_5433/logfile
      
      # The test summary files contain paths with ':' characters, which is not allowed with the upload-artifact actions
      - name: Rename Test Summary Files
        id: test-file-rename
        if: always() && (steps.jdbc.outcome == 'failure' || steps.replication.outcome == 'failure')
        run: |
          cd test/JDBC/Info
          timestamp=`ls -Art | tail -n 1`
          cd $timestamp
          mv $timestamp.diff ../output-diff.diff
          mv "$timestamp"_runSummary.log ../run-summary.log
          cd ..
          # get the replication output diff as well if it is present
          dir_count=`ls | wc -l`
          if [[ $dir_count -eq 2 ]];then
            timestamp=`ls -rt | tail -n 2 | sort -r | tail -n 1`
            cd $timestamp
            mv $timestamp.diff ../replication-output-diff.diff
            mv "$timestamp"_runSummary.log ../replication-run-summary.log
      
      - name: Upload Run Summary 
        if: always() && steps.test-file-rename.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: run-summary.log
          path: test/JDBC/Info/run-summary.log
      
      - name: Upload Output Diff
        if: always() && (steps.jdbc.outcome == 'failure' || steps.replication.outcome == 'failure')
        uses: actions/upload-artifact@v4
        with:
          name: output-diff.diff
          path: test/JDBC/Info/output-diff.diff

      - name: Check and upload coredumps
        if: always() && (steps.jdbc.outcome == 'failure' || steps.replication.outcome == 'failure')
        uses: ./.github/composite-actions/upload-coredump
