name: validate installation/upgrade scripts
on: [pull_request]

jobs:
  run-sql-validation-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: checkout
      - name: Install Python
        id: install-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run tests
        id: run-test
        run: |
          cd test/python
          python3 sql_validation.py
