name: Validate Installation/Upgrade Scripts
on: [push, pull_request]

jobs:
  run-sql-validation-tests:
    runs-on: ubuntu-20.04
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - uses: actions/checkout@v2
        id: checkout
      - name: Install Python
        id: install-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Run tests
        id: run-test
        if: always() && steps.install-python.outcome == 'success'
        run: |
          cd test/python
          python3 sql_validation.py
      - name: Upload artifacts
        if: always() && steps.run-test.outcome == 'failure'
        uses: actions/upload-artifact@v2
        with:
          name: expected-output-files
          path: test/python/output/sql_validation_framework/*
